### ISSUE TITLE
Numpy version compatibility issue

### ISSUE THREAD

**Issue by wangshiyao-1119** [ljuvela/GELP#2]
Hello, thank you for your project! 
However, I encountered an error during runtime, when I run:
 python generate_copysyn.py  --model_dir sessions/pretrained  --input_wav_dir demo_data/wav   --suppress_warnings

error as follows:

WARNING:tensorflow:From /home/sywang/GELP-master/model_causal.py:25: calling Constant.__init__ (from tensorflow.python.
ops.init_ops) with dtype is deprecated and will be removed in a future version.Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "generate_copysyn.py", line 218, in <module>
    copy_synthesis(args)
  File "generate_copysyn.py", line 176, in copy_synthesis
    x_fake_flat = ar_synthesis_filter(exc_fake_flat, a, frame_length, frame_step, nfft)
  File "/home/sywang/GELP-master/sigproc.py", line 166, in ar_synthesis_filter
    A = tf.signal.rfft(a_pad)
  File "/home/sywang/anaconda2/envs/gelp-gpu/lib/python3.7/site-packages/tensorflow_core/python/ops/signal/fft_ops.py",
 line 124, in _rfft    input_tensor = _maybe_pad_for_rfft(input_tensor, fft_rank, fft_length)
  File "/home/sywang/anaconda2/envs/gelp-gpu/lib/python3.7/site-packages/tensorflow_core/python/ops/signal/fft_ops.py",
 line 99, in _maybe_pad_for_rfft    outer_paddings = _array_ops.zeros([outer_dims], fft_length.dtype)
  File "/home/sywang/anaconda2/envs/gelp-gpu/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line
 2338, in zeros    output = _constant_if_small(zero, shape, dtype, name)
  File "/home/sywang/anaconda2/envs/gelp-gpu/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line
 2295, in _constant_if_small    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/home/sywang/anaconda2/envs/gelp-gpu/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/home/sywang/anaconda2/envs/gelp-gpu/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapr
eduction    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/sywang/anaconda2/envs/gelp-gpu/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line
 736, in __array__    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (rfft/Maximum:0) to a numpy array.

How can I solve this? Thank you very much!

**Comment by ljuvela** [comment]
Could be a numpy version issue, I didn't include a specific version in the conda enviroment.
Try rolling back your numpy version, for example
```
conda install numpy=1.17
```

This issue seems similar https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy

**Comment by wangshiyao-1119** [comment]
> Could be a numpy version issue, I didn't include a specific version in the conda enviroment.
> Try rolling back your numpy version, for example
> 
> ```
> conda install numpy=1.17
> ```
> 
> This issue seems similar https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy

Yes, it is a problem with the numpy version, the problem has been solved, thank you very much!

**Comment by ljuvela** [comment]
Thanks for reporting and testing. I added numpy version specifiers to the environment files, closing the issue.
